name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
    env:
      RESULTS_PATH: a11y-results/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test

    - name: Attach Result Artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: a11y-results
        path: a11y-results/

    - name: Generate Report
      id: xunit-viewer
      if: always()
      uses: AutoModality/action-xunit-viewer@v1
      with:
        results: ${{ env.RESULTS_PATH }}

    - name: The generated report
      if: always()
      run: echo "The report is ${{ steps.xunit-viewer.outputs.report-file }}"    
      
    - name: Attach the report
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: alternate-results-path-reports
        path: ${{ env.RESULTS_PATH }}